name: siteisjustapage
favicon: null
layout_spectrum: 0.7764455194119364
typography_spectrum: 0.2128397524356842
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#71A7FE'
    - '#399AE7'
    - '#3B407C'
    - '#547AB1'
    - '#CEAFC0'
  brandStrength: 0.25158702046610415
  lightness: 0.3070246947463602
  saturation: 0.2848866714630276
  rhythmicContrast: 0.7269304385408759
purpose: []
